export const USER_ROLE_REQUEST = 'USER_ROLE_REQUEST';
export const USER_ROLE_SUCCESS = 'USER_ROLE_SUCCESS';
export const USER_ROLE_FAIL = 'USER_ROLE_FAIL';

export const USER_ROLE_CREATE_REQUEST = 'USER_ROLE_CREATE_REQUEST';
export const USER_ROLE_CREATE_SUCCESS = 'USER_ROLE_CREATE_SUCCESS';
export const USER_ROLE_CREATE_FAIL = 'USER_ROLE_CREATE_FAIL';
export const USER_ROLE_CREATE_RESET = 'USER_ROLE_CREATE_RESET';

export const USER_ROLE_UPDATE_REQUEST = 'USER_ROLE_UPDATE_REQUEST';
export const USER_ROLE_UPDATE_SUCCESS = 'USER_ROLE_UPDATE_SUCCESS';
export const USER_ROLE_UPDATE_FAIL = 'USER_ROLE_UPDATE_FAIL';
export const USER_ROLE_UPDATE_RESET = 'USER_ROLE_UPDATE_RESET';

export const USER_ROLE_DELETE_REQUEST = 'USER_ROLE_DELETE_REQUEST';
export const USER_ROLE_DELETE_SUCCESS = 'USER_ROLE_DELETE_SUCCESS';
export const USER_ROLE_DELETE_FAIL = 'USER_ROLE_DELETE_FAIL';
